title: Cart Shed Research
email: webmaster@cart-shed.com
tagline: Contract Research and Development in Sussex
description: >- # this means to ignore newlines until "baseurl:"
  Cart Shed Research is a partnership specialising in research and
  development for sustainably focused business. It has experience in
  the wood industry, in the circular economy and in software project
  management and development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.cart-shed.com" # the base hostname & protocol for your site, e.g. http://example.com
creator: Roland Whitehead
author:
    name: Roland Whitehead
    url: https://cart-shed.com
    email: webmaster@cart-shed.com
twitter_username: 
github_username:  qururoland

github:
    repo: https://github.com/qururoland/cart-shed.github.io

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - '.#*'
  - '/*/.#*'
  - '#*'
  - '/*/#*'
  - 'links/*'
  - 'static/style/#*'
  - 'static/style/.#*'
  - 'static/js/#*'
  - 'static/js/.#*'

#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
version: 0.1
kramdown:
  gfm_quirks: [paragraph_end]
  gfm_emojis: true
  hard_wrap: true
